baseurl = "https://portfolio-hugo.k6khvjkz5t.workers.dev"
title = "Sebastien Sanz de Santamaria"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  description = "Sebastien Sanz de Santamaria, software developer & cultural producer"

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animate__bounce" 

  [[params.navlinks]]
  name = "about"
  url = "about/"

 [[params.navlinks]]
  name = "projects"
  url = "projects/"

 [[params.navlinks]]
  name = "clients"
  url = "clients/"

  # [[params.navlinks]]
  # name = "posts"
  # url = "posts/"